tunnel: 9a59e21c-7e0d-4cac-8502-59bc66436e0f

ingress:
  - hostname: www.visionflow.info
    service: http://logseq-xr-webxr:4000
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s
      tcpKeepAlive: 30s
      keepAliveTimeout: 2m
      keepAliveConnections: 100
      httpHostHeader: www.visionflow.info
      # WebSocket optimizations
      idleTimeout: 1h
      streamTimeout: 4h
  - service: http_status:404

# Connection settings
protocol: quic
no-autoupdate: true

# Logging settings
loglevel: debug

# Metrics settings
metrics: 0.0.0.0:2000

warp-routing:
  enabled: true
