tunnel: 9a59e21c-7e0d-4cac-8502-59bc66436e0f
credentials-file: /etc/cloudflared/cert.pem

ingress:
  - hostname: logseq-xr.jjohare.com
    service: http://logseq-xr-webxr:4000
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s
      tcpKeepAlive: 30s
      keepAliveTimeout: 2m
      keepAliveConnections: 100
  - service: http_status:404

# Connection settings
protocol: quic
no-autoupdate: true

# Logging settings
loglevel: debug

# Metrics settings
metrics: 0.0.0.0:2000
