tunnel: ${TUNNEL_ID}

ingress:
  - hostname: www.${DOMAIN}
    service: http://logseq-xr-webxr:4000
    originRequest:
      noTLSVerify: false
      connectTimeout: 30s
      tcpKeepAlive: 30s
      keepAliveTimeout: 2m
      keepAliveConnections: 100
      httpHostHeader: www.${DOMAIN}
  - service: http_status:404

# Connection settings
protocol: quic
no-autoupdate: true

# Logging settings
loglevel: info

# Metrics settings
metrics: 127.0.0.1:2000
