name: logseq-xr

services:
  webxr-graph:
    build: .
    image: logseq-xr-image:latest
    container_name: logseq-xr-webxr-graph-1
    read_only: false
    networks:
      - logseq_net
      - docker_ragflow  # This is the actual network name created by RAGFlow's compose
    deploy:
      resources:
        limits:
          cpus: '16.0'
          memory: 64G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "4000:4000"
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - BIND_ADDRESS=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - RAGFLOW_BASE_URL=http://ragflow-server/v1/
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./settings.toml:/app/settings.toml:ro
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 4G
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "5"

networks:
  logseq_net:
    driver: bridge
  docker_ragflow:
    external: true  # Use existing RAGFlow network with correct name
