name: logseq-xr

services:
  webxr-graph:
    build: .
    image: logseq-xr-image:latest
    container_name: logseq-xr-webxr
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
    networks:
      logseq_net:
        aliases:
          - webxr-service
      docker_ragflow:
        aliases:
          - webxr-client
    deploy:
      resources:
        limits:
          cpus: '16.0'
          memory: 64G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=0
      - BIND_ADDRESS=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - RAGFLOW_BASE_URL=http://ragflow-server/v1/
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./settings.toml:/app/settings.toml:ro
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 4G
          mode: 1777
      - type: tmpfs
        target: /var/log/nginx
        tmpfs:
          size: 100M
          mode: 0777
      - type: tmpfs
        target: /var/lib/nginx/client_temp
        tmpfs:
          size: 20M
          mode: 0777
      - type: tmpfs
        target: /var/lib/nginx/proxy_temp
        tmpfs:
          size: 20M
          mode: 0777
      - type: tmpfs
        target: /var/lib/nginx/fastcgi_temp
        tmpfs:
          size: 20M
          mode: 0777
      - type: tmpfs
        target: /var/lib/nginx/uwsgi_temp
        tmpfs:
          size: 20M
          mode: 0777
      - type: tmpfs
        target: /var/lib/nginx/scgi_temp
        tmpfs:
          size: 20M
          mode: 0777
      - type: tmpfs
        target: /var/run/nginx
        tmpfs:
          size: 10M
          mode: 0777
      - type: tmpfs
        target: /var/cache/nginx
        tmpfs:
          size: 100M
          mode: 0777
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
        max-file: "5"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
    volumes:
      - ./config.yml:/etc/cloudflared/config.yml:ro
    command: tunnel --loglevel info --config /etc/cloudflared/config.yml run
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      - TUNNEL_ID=${TUNNEL_ID}
      - TUNNEL_METRICS=127.0.0.1:2000
      - TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query
    env_file:
      - .env
    networks:
      logseq_net:
        aliases:
          - cloudflared-service
    depends_on:
      webxr-graph:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  logseq_net:
    name: logseq-xr_logseq_net
    driver: bridge
    internal: true
    enable_ipv6: false
    driver_opts:
      com.docker.network.bridge.name: br-logseq
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  docker_ragflow:
    external: true
