// This file is automatically generated based on data/settings.yaml and client/src/features/settings/config/settings.ts
// Do not modify this file directly. Instead, update the YAML file or the TypeScript interfaces.

import { Settings } from './settings';

export const defaultSettings: Settings = {
  visualisation: {
    nodes: {
      baseColor: '#66d9ef',
      metalness: 0.2,
      opacity: 1.0,
      roughness: 0.7,
      sizeRange: [0.01, 0.15],
      quality: 'medium',
      enableInstancing: false,
      enableHologram: false,
      enableMetadataShape: false,
      enableMetadataVisualisation: true,
    },
    edges: {
      arrowSize: 0.02,
      baseWidth: 0.1,
      color: '#56b6c2',
      enableArrows: false,
      opacity: 0.85,
      widthRange: [0.1, 1.0],
      quality: 'medium',
      enableFlowEffect: false,
      flowSpeed: 1.0,
      flowIntensity: 1.0,
      glowStrength: 1.0,
      distanceIntensity: 1.0,
      useGradient: false,
      gradientColors: ['#ffffff', '#000000'],
    },
    physics: {
      attractionStrength: 0.05,
      boundsSize: 15.0,
      collisionRadius: 0.5,
      damping: 0.95,
      enableBounds: true,
      enabled: true,
      iterations: 100,
      maxVelocity: 0.02,
      repulsionStrength: 0.1,
      springStrength: 0.2,
      repulsionDistance: 2.0,
      massScale: 1.0,
      boundaryDamping: 0.95,
    },
    rendering: {
      ambientLightIntensity: 0.8,
      backgroundColor: '#181c28',
      directionalLightIntensity: 0.7,
      enableAmbientOcclusion: false,
      enableAntialiasing: false,
      enableShadows: false,
      environmentIntensity: 0.7,
      shadowMapSize: '2048', // Default from settingsUIDefinition
      shadowBias: 0.0001, // Default from settingsUIDefinition
      context: 'desktop', // Default from settingsUIDefinition
    },
    animations: {
      enableMotionBlur: false,
      enableNodeAnimations: false,
      motionBlurStrength: 0.2,
      selectionWaveEnabled: false,
      pulseEnabled: false,
      pulseSpeed: 0.8,
      pulseStrength: 0.6,
      waveSpeed: 0.5,
    },
    labels: {
      desktopFontSize: 0.15,
      enableLabels: true,
      textColor: '#f8f8f2',
      textOutlineColor: '#181c28',
      textOutlineWidth: 0.01,
      textResolution: 32,
      textPadding: 0.3,
      billboardMode: 'camera',
    },
    bloom: {
      edgeBloomStrength: 0.4,
      enabled: false,
      environmentBloomStrength: 2.0,
      nodeBloomStrength: 3.0,
      radius: 2.0,
      strength: 3.0,
      threshold: 0.4, // Default from settingsUIDefinition
    },
    hologram: {
      ringCount: 1,
      ringColor: '#c2a200',
      ringOpacity: 0.001,
      sphereSizes: [4, 8],
      ringRotationSpeed: 10.0,
      enableBuckminster: false,
      buckminsterSize: 10,
      buckminsterOpacity: 0.05,
      enableGeodesic: false,
      geodesicSize: 10,
      geodesicOpacity: 0.05,
      enableTriangleSphere: false,
      triangleSphereSize: 10,
      triangleSphereOpacity: 0.05,
      globalRotationSpeed: 3,
    },
    camera: { // Default values for camera, assuming a common setup
      fov: 75,
      near: 0.1,
      far: 2000,
      position: { x: 0, y: 10, z: 50 },
      lookAt: { x: 0, y: 0, z: 0 },
    },
  },
  system: {
    websocket: {
      binaryChunkSize: 2048,
      binaryUpdateRate: 30, // Not in settings.ts, but in YAML
      minUpdateRate: 5, // Not in settings.ts, but in YAML
      maxUpdateRate: 60, // Not in settings.ts, but in YAML
      motionThreshold: 0.05, // Not in settings.ts, but in YAML
      motionDamping: 0.9, // Not in settings.ts, but in YAML
      binaryMessageVersion: 1, // Not in settings.ts, but in YAML
      compressionEnabled: false,
      compressionThreshold: 512,
      heartbeatInterval: 10000, // Not in settings.ts, but in YAML
      heartbeatTimeout: 600000, // Not in settings.ts, but in YAML
      maxConnections: 100, // Not in settings.ts, but in YAML
      maxMessageSize: 10485760, // Not in settings.ts, but in YAML
      reconnectAttempts: 5,
      reconnectDelay: 1000,
      updateRate: 60,
    },
    debug: {
      enabled: false,
      enableDataDebug: false,
      enableWebsocketDebug: false,
      logBinaryHeaders: false,
      logFullJson: false,
      logLevel: 'warn',
      logFormat: 'json', // Not in settings.ts, but in YAML
      enablePhysicsDebug: false, // Default from settingsUIDefinition
      enableNodeDebug: false, // Default from settingsUIDefinition
      enableShaderDebug: false, // Default from settingsUIDefinition
      enableMatrixDebug: false, // Default from settingsUIDefinition
      enablePerformanceDebug: false, // Default from settingsUIDefinition
    },
    persistSettings: true, // Default from settingsUIDefinition
    customBackendUrl: '', // Default from settingsUIDefinition
  },
  xr: {
    enabled: true, // Default from settingsUIDefinition
    clientSideEnableXR: false, // Default from settingsUIDefinition
    displayMode: 'inline',
    roomScale: 1.0,
    spaceType: 'local-floor',
    quality: 'medium',
    enableHandTracking: true,
    handMeshEnabled: true,
    handMeshColor: '#4287f5',
    handMeshOpacity: 0.3,
    handPointSize: 0.006,
    handRayEnabled: true,
    handRayColor: '#4287f5',
    handRayWidth: 0.003,
    gestureSmoothing: 0.7,
    enableHaptics: true,
    hapticIntensity: 0.3,
    dragThreshold: 0.08,
    pinchThreshold: 0.3,
    rotationThreshold: 0.08,
    interactionRadius: 0.15,
    movementSpeed: 0.08,
    deadZone: 0.12,
    movementAxesHorizontal: 2,
    movementAxesVertical: 3,
    enableLightEstimation: false,
    enablePlaneDetection: false,
    enableSceneUnderstanding: false,
    planeColor: '#4287f5',
    planeOpacity: 0.001,
    planeDetectionDistance: 3.0,
    showPlaneOverlay: false,
    snapToFloor: false,
    enablePassthroughPortal: false,
    passthroughOpacity: 0.8,
    passthroughBrightness: 1.1,
    passthroughContrast: 1.2,
    portalSize: 2.5,
    portalEdgeColor: '#4287f5',
    portalEdgeWidth: 0.02,
    controllerModel: 'default',
    renderScale: 1.0,
    interactionDistance: 1.0,
    locomotionMethod: 'teleport',
    teleportRayColor: '#ffffff',
    controllerRayColor: '#ffffff',
  },
  auth: {
    enabled: false,
    provider: '',
    required: false,
  },
  ragflow: {
    agentId: 'aa2e328812ef11f083dc0a0d6226f61b',
    timeout: 30,
    maxRetries: 3,
    chatId: '',
  },
  perplexity: {
    apiKey: '',
    model: 'llama-3.1-sonar-small-128k-online',
    apiUrl: '',
    maxTokens: 4096,
    temperature: 0.5,
    topP: 0.9,
    presencePenalty: 0.0,
    frequencyPenalty: 0.0,
    timeout: 30,
    rateLimit: 100,
  },
  openai: {
    apiKey: '',
    baseUrl: '',
    timeout: 30,
    rateLimit: 100,
  },
  kokoro: {
    apiUrl: 'http://pedantic_morse:8880',
    defaultVoice: 'af_heart',
    defaultFormat: 'mp3',
    defaultSpeed: 1.0,
    timeout: 30,
    stream: true,
    returnTimestamps: true,
    sampleRate: 24000,
  },
};